Document: naviserver-nsdbpg
Title: Debian naviserver-nsdbpg Manual
Author: <insert document author here>
Abstract: This manual describes what naviserver-nsdbpg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/naviserver-nsdbpg/naviserver-nsdbpg.sgml.gz

Format: postscript
Files: /usr/share/doc/naviserver-nsdbpg/naviserver-nsdbpg.ps.gz

Format: text
Files: /usr/share/doc/naviserver-nsdbpg/naviserver-nsdbpg.text.gz

Format: HTML
Index: /usr/share/doc/naviserver-nsdbpg/html/index.html
Files: /usr/share/doc/naviserver-nsdbpg/html/*.html
